"""add nvplay match id

Revision ID: 0f7fad5a19a4
Revises: a0bfee6cc133
Create Date: 2026-05-22 21:50:50.028849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7fad5a19a4'
down_revision: Union[str, Sequence[str], None] = 'a0bfee6cc133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('nvplay_match_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_matches_nvplay_match_id'), 'matches', ['nvplay_match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_nvplay_match_id'), table_name='matches')
    op.drop_column('matches', 'nvplay_match_id')
    # ### end Alembic commands ###
