"""add match season

Revision ID: 1af6cecf6249
Revises: 0f7fad5a19a4
Create Date: 2026-05-22 22:26:24.965407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af6cecf6249'
down_revision: Union[str, Sequence[str], None] = '0f7fad5a19a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('season', sa.String(), nullable=False))
    op.create_index(op.f('ix_matches_season'), 'matches', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_season'), table_name='matches')
    op.drop_column('matches', 'season')
    # ### end Alembic commands ###
