"""add team id to performances

Revision ID: 5f29e6e4803c
Revises: 1af6cecf6249
Create Date: 2026-05-23 08:20:05.442209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f29e6e4803c'
down_revision: Union[str, Sequence[str], None] = '1af6cecf6249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batting_innings', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_batting_innings_team_id'), 'batting_innings', ['team_id'], unique=False)
    op.add_column('bowling_spells', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bowling_spells_team_id'), 'bowling_spells', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bowling_spells', type_='foreignkey')
    op.drop_index(op.f('ix_bowling_spells_team_id'), table_name='bowling_spells')
    op.drop_column('bowling_spells', 'team_id')
    op.drop_constraint(None, 'batting_innings', type_='foreignkey')
    op.drop_index(op.f('ix_batting_innings_team_id'), table_name='batting_innings')
    op.drop_column('batting_innings', 'team_id')
    # ### end Alembic commands ###
