"""initial schema

Revision ID: a0bfee6cc133
Revises: 
Create Date: 2026-05-22 21:38:09.897614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bfee6cc133'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('team_1_id', sa.Integer(), nullable=True),
    sa.Column('team_2_id', sa.Integer(), nullable=True),
    sa.Column('team_1_score', sa.String(), nullable=True),
    sa.Column('team_2_score', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_2_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batting_innings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('batting_position', sa.Integer(), nullable=True),
    sa.Column('dismissal', sa.String(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('balls', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('fours', sa.Integer(), nullable=False),
    sa.Column('sixes', sa.Integer(), nullable=False),
    sa.Column('not_out', sa.Boolean(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_wicket_keeper', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batting_innings_match_id'), 'batting_innings', ['match_id'], unique=False)
    op.create_index(op.f('ix_batting_innings_player_id'), 'batting_innings', ['player_id'], unique=False)
    op.create_table('bowling_spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('overs', sa.String(), nullable=False),
    sa.Column('balls_bowled', sa.Integer(), nullable=False),
    sa.Column('maidens', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('wickets', sa.Integer(), nullable=False),
    sa.Column('economy', sa.Float(), nullable=False),
    sa.Column('wides', sa.Integer(), nullable=False),
    sa.Column('no_balls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bowling_spells_match_id'), 'bowling_spells', ['match_id'], unique=False)
    op.create_index(op.f('ix_bowling_spells_player_id'), 'bowling_spells', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bowling_spells_player_id'), table_name='bowling_spells')
    op.drop_index(op.f('ix_bowling_spells_match_id'), table_name='bowling_spells')
    op.drop_table('bowling_spells')
    op.drop_index(op.f('ix_batting_innings_player_id'), table_name='batting_innings')
    op.drop_index(op.f('ix_batting_innings_match_id'), table_name='batting_innings')
    op.drop_table('batting_innings')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
